package com.example.ui_fishlist.ui.test

const val TAG_FISH_SEARCH_BAR = "TAG_HERO_SEARCH_BAR"
const val TAG_FISH_SPECIES_NAME = "TAG_FISH_SPECIES_NAME"
const val TAG_FISH_FILTER_BTN = "TAG_FISH_FILTER_BTN"
const val TAG_FISH_FILTER_DIALOG = "TAG_FISH_FILTER_DIALOG"
const val TAG_FISH_FILTER_DIALOG_DONE = "TAG_FISH_FILTER_DIALOG_DONE"
const val TAG_FISH_FILTER_FISH_CHECKBOX = "TAG_FISH_FILTER_FISH_CHECKBOX"
const val TAG_FISH_FILTER_DESC = "TAG_FISH_FILTER_DESC"
const val TAG_FISH_FILTER_ASC = "TAG_FISH_FILTER_ASC"
const val TAG_FISH_FILTER_INT_CHECKBOX = "TAG_FISH_FILTER_INT_CHECKBOX"
const val TAG_FISH_SCIENTIFIC_NAME = "TAG_HERO_PRIMARY_ATTRIBUTE"